version: "3.9"

services:
    proxy:
        depends_on:
        - backend
        image: ulticlipper-proxy-prod
        container_name: ulticlipper-proxy-prod
        environment:
            ALLOWED_HOSTS: ulticlipper.jessmuir.com
        ports:
            - "80:80"
            - "443:443"
        networks:
            ulticlipper: {}
        volumes:
            - caddy_data:/data
    backend:
        depends_on:
        - database
        image: ulticlipper-backend-prod
        container_name: ulticlipper-backend-prod
        environment:
            ENV_NAME: prod
        networks:
            ulticlipper: {}
        restart: always
    database:
        image: postgres:14.5
        container_name: ulticlipper-database-prod
        environment:
            POSTGRES_USER: backend
            POSTGRES_PASSWORD: good_password
        networks:
            ulticlipper: {}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always

volumes:
    caddy_data:
        external: false
    postgres_data:
        external: false

networks:
    ulticlipper:
        driver: bridge
