version: "3.9"

services:
    proxy:
        depends_on:
        - backend
        image: ulticlipper-proxy-ci
        build:
            dockerfile: deploy/dockerfiles/caddy.dockerfile
        container_name: ulticlipper-proxy-ci
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./deploy/caddyfiles/ci.Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
    backend:
        depends_on:
        - database
        image: ulticlipper-backend-ci
        build:
            dockerfile: deploy/dockerfiles/django.dockerfile
        container_name: ulticlipper-backend-ci
        environment:
            ENV_NAME: ci
        volumes:
            - .:/app:z
        restart: always
    database:
        image: postgres:14.5
        container_name: ulticlipper-database-ci
        environment:
          POSTGRES_USER: backend
          POSTGRES_PASSWORD: good_password
        restart: always

volumes:
    caddy_data:
        external: false
