# Generated by Django 4.1.1 on 2022-10-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_tag_backend_tag_name_194adf_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClipTags',
        ),
    ]
