# Generated by Django 4.1.1 on 2022-10-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_cliptags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='value',
        ),
    ]
