name: Run unit and integration tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  utest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run unit tests
      run: ./dev test
    - name: Run integration tests
      run: ./dev itest

